on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working directory to the java-app directory
        # works only for the shell.
        working-directory: java-app
    permissions:
      deployments: write
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: do quality checks
        uses: ./.github/actions/code-quality-java
        with:
          working-directory: java-app
      - name: run maven command to build the app
        run: ./mvnw clean install
      - name: upload the artifact2
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

